version: "3.8"
services:
    laravel:
        image: simonloudev/co2:latest
        container_name: laravel
        restart: always
        expose:
            - 8080
        networks:
            stack-network:
                ipv4_address: 172.20.0.250
        labels:
            - "traefik.enable=true"
            - "traefik.docker.network=stack-network"
            - "traefik.http.routers.laravel.rule=Host(`co2.loritz.fr`)"
            - "traefik.http.routers.laravel.service=laravel@docker"
            - "traefik.http.services.laravel.loadbalancer.server.port=8080"
            - "traefik.http.routers.laravel.entrypoints=http,https"


networks:
    stack-network:
        external: true
