version: "3.8"
services:
    mosquitto:
        image: eclipse-mosquitto
        container_name: broker_mqtt
        restart: always
        volumes:
            - mosquitto:/mosquitto
        ports:
            - 1883:1883
            - 9001:9001
    socketi:
        image: quay.io/soketi/soketi:1.4-16-debian
        container_name: socketi
        restart: always
        ports:
            - 6001:6001
            - 9601:9601
        environment:
            - SOKETI_DEFAULT_APP_ID=laravelApp
            - SOKETI_DEFAULT_APP_KEY=appkey
            - SOKETI_DEFAULT_APP_SECRET=app-secret
            - SOKETI_DEBUG=1
    mysql:
        image: mysql
        container_name: mysql_bdd
        restart: always
        ports:
            -   3306:3306
        environment:
            - MYSQL_ROOT_PASSWORD=test
        volumes:
            - mysql_data:/var/lib/mysql

    redis:
        image: redis
        container_name: redis
        restart: always
        ports:
            - 6379:6379
        volumes:
            - redis-data:/data

    chirpstack:
        image: chirpstack/chirpstack:4
        command: -c /etc/chirpstack
        restart: unless-stopped
        volumes:
            - ./docker_configuration/chirpstack:/etc/chirpstack
            - ./lorawan-devices:/opt/lorawan-devices
        depends_on:
            - postgres
            - mosquitto
            - redis
        environment:
            - MQTT_BROKER_HOST=mosquitto
            - REDIS_HOST=redis
            - POSTGRESQL_HOST=postgres
        ports:
            - 8080:8080

    chirpstack-gateway-bridge:
        image: chirpstack/chirpstack-gateway-bridge:4
        restart: unless-stopped
        ports:
            - 1700:1700/udp
        volumes:
            - ./docker_configuration/chirpstack-gateway-bridge:/etc/chirpstack-gateway-bridge
        environment:
            - INTEGRATION__MQTT__EVENT_TOPIC_TEMPLATE=eu868/gateway/{{ .GatewayID }}/event/{{ .EventType }}
            - INTEGRATION__MQTT__STATE_TOPIC_TEMPLATE=eu868/gateway/{{ .GatewayID }}/state/{{ .StateType }}
            - INTEGRATION__MQTT__COMMAND_TOPIC_TEMPLATE=eu868/gateway/{{ .GatewayID }}/command/#
        depends_on:
            - mosquitto

    chirpstack-gateway-bridge-basicstation:
        image: chirpstack/chirpstack-gateway-bridge:4
        restart: unless-stopped
        command: -c /etc/chirpstack-gateway-bridge/chirpstack-gateway-bridge-basicstation-eu868.toml
        ports:
            - 3001:3001
        volumes:
            - ./docker_configuration/chirpstack-gateway-bridge:/etc/chirpstack-gateway-bridge
        depends_on:
            - mosquitto

    chirpstack-rest-api:
        image: chirpstack/chirpstack-rest-api:4
        restart: unless-stopped
        command: --server chirpstack:8080 --bind 0.0.0.0:8090 --insecure
        ports:
            - 8090:8090
        depends_on:
            - chirpstack

    postgres:
        image: postgres:14-alpine
        restart: unless-stopped
        volumes:
            - ./docker_configuration/postgresql/initdb:/docker-entrypoint-initdb.d
            - postgresqldata:/var/lib/postgresql/data
        environment:
            - POSTGRES_PASSWORD=root




volumes:
    mosquitto:
    mysql_data:
    redis-data:
