version: "3.8"
services:
    laravel:
        image: simonloudev/co2
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel
        restart: always
        expose:
            - 8080
        networks:
            stack-network:
                ipv4_address: 172.20.0.250


networks:
    stack-network:
        external: true
